In [2]:
                                # US DATA OF STATES
import numpy as np                                 
import pandas as pd
pop = pd.read_csv('C:\\Users\\Admin\\Documents\\Python practice\\data-USstates-master\\state-population.csv')
areas = pd.read_csv('C:\\Users\\Admin\\Documents\\Python practice\\data-USstates-master\\state-areas.csv')
abbrevs = pd.read_csv('C:\\Users\\Admin\\Documents\\Python practice\\data-USstates-master\\state-abbrevs.csv')
print(pop.head())
print(areas.head())
print(abbrevs.head())            
print('----------------------------------Step1: Many to one Merge---------------------------------------------------')
print('This step will give us the full state name from abbrev dataframe and will be added to pop DataFrame')
print('Merge will be on basis of state column of pop DataFrame and abbreviation column of abbrev')
merged = pd.merge(pop, abbrevs, how='outer', left_on='state/region', right_on='abbreviation').drop('abbreviation', axis=1)
print(merged.head())
print('Check for any mis-match: It can be done by checking if there is any NaN value present in any row')
print(merged.isnull().any())
print('It looks like there are some null values in population; we shall find it out by boolean masking!!')
print(merged[merged['population'].isnull()].head())
print('As the states column is also showing True in previous table: which means that some States name are missing')
merged.loc[merged['state'].isnull(), 'state/region'].unique()
print('PR and USA abbrevations full names are missing, So we will add them..')
merged.loc[merged['state/region'] == 'PR', 'state'] = 'Peurto Rico'
merged.loc[merged['state/region'] == 'USA', 'state'] = 'Unites States'
print('After adding names of states we shall check it')
print(merged.isnull().any())
print('Now there are no NaN states, but there are NaN population beacuse that data is not provided in the Csv file.')
print('------------------------------------Step2: Merge Area DataFrame to merge DataFrame------------------------------------')
final = pd.merge(merged, areas, on='state', how='left')
print(final.head())
print('Now we should check if there are some mismathch in final dataframe.')
print(final.isnull().any())
print('As seen there is some mismatch in area, so we will find it out....')
print(final['state'][final['area (sq. mi)'].isnull()].unique())
print('We will remove these two states')
final.dropna(inplace=True)
print(final.isnull().any())
print('There are no NaN values in the final DataFrame')
data2010 = final.query("year == 2010 & ages == 'total'")
print(data2010.head())
print('All the values of year 2010 and ages total')
data2010.set_index('state', inplace=True)
print(data2010.head())
density = data2010['population']/data2010['area (sq. mi)']
print('=================================================POPULATION DENSITY=================================================')
print(density)
print('Thus the population density of 2010 year is calculated.............')

  state/region     ages  year  population
0           AL  under18  2012   1117489.0
1           AL    total  2012   4817528.0
2           AL  under18  2010   1130966.0
3           AL    total  2010   4785570.0
4           AL  under18  2011   1125763.0
        state  area (sq. mi)
0     Alabama          52423
1      Alaska         656425
2     Arizona         114006
3    Arkansas          53182
4  California         163707
        state abbreviation
0     Alabama           AL
1      Alaska           AK
2     Arizona           AZ
3    Arkansas           AR
4  California           CA
----------------------------------Step1: Many to one Merge---------------------------------------------------
This step will give us the full state name from abbrev dataframe and will be added to pop DataFrame
Merge will be on basis of state column of pop DataFrame and abbreviation column of abbrev
  state/region     ages  year  population    state
0           AL  under18  2012   1117489.0  Alabama
1           AL    total  2012   4817528.0  Alabama
2           AL  under18  2010   1130966.0  Alabama
3           AL    total  2010   4785570.0  Alabama
4           AL  under18  2011   1125763.0  Alabama
Check for any mis-match: It can be done by checking if there is any NaN value present in any row
state/region    False
ages            False
year            False
population       True
state            True
dtype: bool
It looks like there are some null values in population; we shall find it out by boolean masking!!
     state/region     ages  year  population state
2448           PR  under18  1990         NaN   NaN
2449           PR    total  1990         NaN   NaN
2450           PR    total  1991         NaN   NaN
2451           PR  under18  1991         NaN   NaN
2452           PR    total  1993         NaN   NaN
As the states column is also showing True in previous table: which means that some States name are missing
PR and USA abbrevations full names are missing, So we will add them..
After adding names of states we shall check it
state/region    False
ages            False
year            False
population       True
state           False
dtype: bool
Now there are no NaN states, but there are NaN population beacuse that data is not provided in the Csv file.
------------------------------------Step2: Merge Area DataFrame to merge DataFrame------------------------------------
  state/region     ages  year  population    state  area (sq. mi)
0           AL  under18  2012   1117489.0  Alabama        52423.0
1           AL    total  2012   4817528.0  Alabama        52423.0
2           AL  under18  2010   1130966.0  Alabama        52423.0
3           AL    total  2010   4785570.0  Alabama        52423.0
4           AL  under18  2011   1125763.0  Alabama        52423.0
Now we should check if there are some mismathch in final dataframe.
state/region     False
ages             False
year             False
population        True
state            False
area (sq. mi)     True
dtype: bool
As seen there is some mismatch in area, so we will find it out....
['Peurto Rico' 'Unites States']
We will remove these two states
state/region     False
ages             False
year             False
population       False
state            False
area (sq. mi)    False
dtype: bool
There are no NaN values in the final DataFrame
    state/region   ages  year  population       state  area (sq. mi)
3             AL  total  2010   4785570.0     Alabama        52423.0
91            AK  total  2010    713868.0      Alaska       656425.0
101           AZ  total  2010   6408790.0     Arizona       114006.0
189           AR  total  2010   2922280.0    Arkansas        53182.0
197           CA  total  2010  37333601.0  California       163707.0
All the values of year 2010 and ages total
           state/region   ages  year  population  area (sq. mi)
state
Alabama              AL  total  2010   4785570.0        52423.0
Alaska               AK  total  2010    713868.0       656425.0
Arizona              AZ  total  2010   6408790.0       114006.0
Arkansas             AR  total  2010   2922280.0        53182.0
California           CA  total  2010  37333601.0       163707.0
=================================================POPULATION DENSITY=================================================
state
Alabama                   91.287603
Alaska                     1.087509
Arizona                   56.214497
Arkansas                  54.948667
California               228.051342
Colorado                  48.493718
Connecticut              645.600649
Delaware                 460.445752
District of Columbia    8898.897059
Florida                  286.597129
Georgia                  163.409902
Hawaii                   124.746707
Idaho                     18.794338
Illinois                 221.687472
Indiana                  178.197831
Iowa                      54.202751
Kansas                    34.745266
Kentucky                 107.586994
Louisiana                 87.676099
Maine                     37.509990
Maryland                 466.445797
Massachusetts            621.815538
Michigan                 102.015794
Minnesota                 61.078373
Mississippi               61.321530
Missouri                  86.015622
Montana                    6.736171
Nebraska                  23.654153
Nevada                    24.448796
New Hampshire            140.799273
New Jersey              1009.253268
New Mexico                16.982737
New York                 356.094135
North Carolina           177.617157
North Dakota               9.537565
Ohio                     257.549634
Oklahoma                  53.778278
Oregon                    39.001565
Pennsylvania             275.966651
Rhode Island             681.339159
South Carolina           144.854594
South Dakota              10.583512
Tennessee                150.825298
Texas                     93.987655
Utah                      32.677188
Vermont                   65.085075
Virginia                 187.622273
Washington                94.557817
West Virginia             76.519582
Wisconsin                 86.851900
Wyoming                    5.768079
dtype: float64
Thus the population density of 2010 year is calculated.............